name: Deploy Database Changes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/update@v4.23.0
        with:
          changelogFile: "./db/changelog/master.xml"
          url: "${{ secrets.PG_URL }}"
          database: "${{ secrets.PG_DATABASE_NAME }}"
          username: "${{ secrets.PG_USERNAME }}"
          password: "${{ secrets.PG_PWD }}"
          defaultSchemaName: "${{ secrets.PG_DB_SCHEMA }}"

          