name: Deploy Database Changes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Liquibase Update Action
      - uses: liquibase-github-actions/update@v4.23.0
        with:
          liquibase-version: 4.3.5
          change-log: db/changelog/master.xml
          url: jdbc:postgresql://localhost:5432/mydatabase
          username: myusername
          password: mypassword